DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
ID NUMBER(10) NOT NULL,
FIRST_NAME VARCHAR(30) DEFAULT NULL,
LAST_NAME VARCHAR(30) DEFAULT NULL,
EMAIL VARCHAR(20) DEFAULT NULL,
PRIMARY KEY (ID)
);

DROP SEQUENCE CUSTOMER_ID_SEQ;
CREATE SEQUENCE CUSTOMER_ID_SEQ;

INSERT INTO CUSTOMER VALUES(CUSTOMER_ID_SEQ.NEXTVAL,'Prashant','Choudhary','p@s.com');
INSERT INTO CUSTOMER VALUES(CUSTOMER_ID_SEQ.NEXTVAL,'Anusha','Sathu','a@s.com');

SELECT * FROM CUSTOMER;